services:
  api:
    build: .
    command: sh -c "fastapi run /app/api/run.py --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      ENV_STATE: dev
      DEV_DATABASE_URL: postgresql+aiopg://blink:blink@postgres:5432/blink
      DEV_CLICKHOUSE_URL: clickhouse://default@clickhouse:8123/blink_logs
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./api/:/app/api/
    depends_on:
      - postgres
      - redis
      - clickhouse

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: blink
      POSTGRES_PASSWORD: blink
      POSTGRES_DB: blink
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    environment:
      CLICKHOUSE_DB: blink_logs
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
