services:
  api:
    build: .
    command: sh -c "fastapi run /app/src/start.py --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: postgresql://blink:blink@postgres:5432/blink
      REDIS_URL: redis://redis:6379/0
      CLICKHOUSE_HOST: clickhouse
    volumes:
      - ./src/:/app/src/
    depends_on:
      - postgres
      - redis
      - clickhouse

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: blink
      POSTGRES_PASSWORD: blink
      POSTGRES_DB: blink
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
